# Generated by Django 3.0.5 on 2020-05-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Цепочка', 'Цепочка'), ('Расчетная задача', 'Расчетная задача')], max_length=60)),
                ('content_1', models.CharField(blank=True, max_length=100, verbose_name='Текст задания')),
                ('content_2', models.ImageField(blank=True, upload_to='', verbose_name='Фото задания')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.Level', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['title'],
            },
        ),
    ]
