# Generated by Django 3.0.5 on 2020-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Класс'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
