# Generated by Django 3.0.5 on 2020-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20200504_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content_2',
            field=models.ImageField(blank=True, upload_to='media/task_images', verbose_name='Фото задания'),
        ),
    ]
