# Generated by Django 3.0.5 on 2020-05-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20200505_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content_2',
            field=models.ImageField(blank=True, upload_to='task_images', verbose_name='Фото задания'),
        ),
    ]
