# Generated by Django 3.0.5 on 2020-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20200505_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], verbose_name='Класс'),
        ),
    ]
