# Generated by Django 3.0.5 on 2020-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_auto_20200510_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Автор'),
        ),
    ]
