# Generated by Django 3.0.5 on 2020-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_auto_20200512_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content_1',
            field=models.TextField(blank=True, max_length=700, verbose_name='Текст задания'),
        ),
    ]
